src/java/org/abepomi/model/Extras.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.abepomi.model;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 *
 * @author Julianno
 */
@Entity
@Table(name = "extras", schema = "public")
@IdClass(ExtrasPk.class)
public class Extras implements Serializable {

    public Extras() {
    }

    public Extras(String descricao, Double valor) {
        this.descricao = descricao;
        this.valor = valor;
    }

    

    @Id
    private int id;

    @Id
    private Associado associado;

    @Id
    private Referencia referencia;

    @Column(name="descricao")
    private String descricao;

    @Column(name="valor", precision=10, scale=2)
    private Double valor;

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Double getValor() {
        return valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    public Associado getAssociado() {
        return associado;
    }

    public void setAssociado(Associado associado) {
        this.associado = associado;
    }

    public Referencia getReferencia() {
        return referencia;
    }

    public void setReferencia(Referencia referencia) {
        this.referencia = referencia;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Extras other = (Extras) obj;
        if (this.id != other.id) {
            return false;
        }
        if (this.associado != other.associado && (this.associado == null || !this.associado.equals(other.associado))) {
            return false;
        }
        if (this.referencia != other.referencia && (this.referencia == null || !this.referencia.equals(other.referencia))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + this.id;
        hash = 79 * hash + (this.associado != null ? this.associado.hashCode() : 0);
        hash = 79 * hash + (this.referencia != null ? this.referencia.hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "Extras{" + "id=" + id + "associado=" + associado + "referencia=" + referencia + "descricao=" + descricao + "valor=" + valor + '}';
    }

}

src/java/org/abepomi/mb/FatMB.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.abepomi.mb;

import java.io.Serializable;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.abepomi.dao.DAOFactory;
import org.abepomi.dao.ExtrasDAO;
import org.abepomi.dao.FaturamentoDAO;
import org.abepomi.dao.commons.DAOException;
import org.abepomi.dao.util.DetalheTelefoniaUtil;
import org.abepomi.model.Associacao;
import org.abepomi.model.Associado;
import org.abepomi.model.Extras;
import org.abepomi.model.Faturamento;
import org.abepomi.model.Referencia;
import org.abepomi.model.cobranca.Parcela;
import org.abepomi.model.cobranca.util.TituloUtil;
import org.abepomi.model.util.Categoria;
import org.abepomi.model.util.Status;

/**
 *
 * @author Julianno
 */
public class FatMB implements Serializable {

    private Referencia referencia;
    private Extras extra;
    private Date vencimento = null;
    private boolean naoDebitados = false;

    public FatMB() {
        referencia = new Referencia();
        extra = new Extras();
    }

    public Extras getExtra() {
        return extra;
    }

    public void setExtra(Extras extra) {
        this.extra = extra;
    }

    public Referencia getReferencia() {
        return referencia;
    }

    public void setReferencia(Referencia referencia) {
        this.referencia = referencia;
    }

    public Date getVencimento() {
        return vencimento;
    }

    public void setVencimento(Date vencimento) {
        this.vencimento = vencimento;
    }

    public List<Referencia> getReferencias() {
        return DAOFactory.createReferenciaDAO().buscaRefSemFaturamento();
    }

    public List<Referencia> getTodasReferencias() throws DAOException {
        return DAOFactory.createReferenciaDAO().buscaTodasDecrescente();
    }

    public boolean isNaoDebitados() {
        return naoDebitados;
    }

    public void setNaoDebitados(boolean naoDebitados) {
        this.naoDebitados = naoDebitados;
    }

    public String salvarReferencia() {
        try {
            DAOFactory.createReferenciaDAO().addEntity(referencia);
            referencia = new Referencia();
        } catch (DAOException ex) {
            Logger.getLogger(AssociacaoMB.class.getName()).log(Level.SEVERE, "Erro ao salvar referência!", ex);
            return "falha";
        }
        return "sucesso";
    }

    public String gerarReferencia() {

        Referencia r = DAOFactory.createReferenciaDAO().buscarUltima();
        if (null == r) {
            referencia.setRef(new SimpleDateFormat("MMyyyy").format(new Date()));
        }else if(r.isFaturado()){
            GregorianCalendar c = new GregorianCalendar();
            try {
                c.setTime(new SimpleDateFormat("MMyyyy").parse(r.getRef()));
                c.add(GregorianCalendar.MONTH, 1);
                referencia.setRef(new SimpleDateFormat("MMyyyy").format(c.getTime()));
            } catch (ParseException ex) {
                Logger.getLogger(FatMB.class.getName()).log(Level.SEVERE, "Erro...", ex);
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Erro ao parsear data!", null));
                return "falha";
            }
        }else{
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Existe uma referência sem faturar!", null));
            return "falha";
        }
        referencia.setGeracao(new Date());
        referencia.setFaturado(false);
        return "referencia";
    }

    public String gerarFaturamento() throws DAOException {

        /*
         * Colocar aqui comparação entre quantidade de contratos e fechamento a faturar...
         * se igual continua, senão para!
         */

        List<Associado> associados = DAOFactory.createAssociadoDAO().findAll();
        DecimalFormat df = new DecimalFormat("0.00", DecimalFormatSymbols.getInstance(Locale.ENGLISH));
        Associacao aso = DAOFactory.createAssociacaoDAO().findById(1);
        Double contribuicao = aso.getMultContribuicao() * aso.getUnContribuicao() / 100;
        FaturamentoDAO fatDAO = DAOFactory.createFaturamentoDAO();

        DAOFactory.createFechamentoTelefoniaDAO().atualizarReferencia(referencia);

        for (Associado ass : associados) {
            if (!ass.getStatus().equals(Status.I)) {
                Faturamento fat = new Faturamento();
                fat.setReferencia(referencia);
                fat.setAssociado(ass);
                fat.setServicos(0.00);
                if (ass.isConveniado()) {
                    fat.setMensalidade(0.00);
                } else {
                    if (ass.getCategoria().equals(Categoria.C)) {
                        fat.setMensalidade(Double.parseDouble(df.format(contribuicao * 3.00)));
                    } else if (ass.getCategoria().equals(Categoria.F) || ass.getCategoria().equals(Categoria.T)) {
                        fat.setMensalidade(Double.parseDouble(df.format(contribuicao * 2.00)));
                    } else {
                        fat.setMensalidade(0.00);
                    }
                }
                fat.setExtra(DAOFactory.createExtrasDAO().totalPorAssociado(ass, referencia));

                DetalheTelefoniaUtil tel = DAOFactory.createDetalheDAO().getTotalPorReferenciaAssociado(referencia.getId(), ass.getId());
                fat.setTelefonia(tel.getTotal());
                fat.setVivo(DAOFactory.createDetalheVivoDAO().totalVivoPorAssociado(ass.getId()));

                List<Parcela> parcelas = DAOFactory.createParcelaDAO().parcelasAFaturar(ass.getId());
                if (null != parcelas) {
                    for (Parcela p : parcelas) {
                        fat.setParcelas(fat.getParcelas().add(p.getValor()));
                        p.setSituacao(6);
                        p.setReferencia(referencia);
                        DAOFactory.createParcelaDAO().updateEntity(p);
                    }
                }


                fatDAO.addEntity(fat);
            }
        }
        referencia.setFaturado(true);
        DAOFactory.createReferenciaDAO().updateEntity(referencia);
        DAOFactory.createFaturaVivoDAO().atualizarNaoFaturadas(referencia.getId());

        return "sucesso";
    }

    public String salvarExtra() {
        ExtrasDAO exDAO = DAOFactory.createExtrasDAO();
        try {
            extra.setId(exDAO.proximaId());
            exDAO.addEntity(extra);
            extra = new Extras();
        } catch (DAOException ex) {
            Logger.getLogger(FatMB.class.getName()).log(Level.SEVERE, "Erro: org.abepomi.mb.FatMB.salvarExtra()", ex);
            return "falha";
        }
        return "sucesso";
    }

    public String gerarBoletos() {
        List<Faturamento> fat = null;
        if (naoDebitados) {
            fat = DAOFactory.createFaturamentoDAO().faturamentoAssociadoNDebitado(referencia);
        } else {
            fat = DAOFactory.createFaturamentoDAO().faturamentoAssociadoBoleto(referencia);
        }
        try {
            TituloUtil.gerarTitulosFaturamentos(fat, vencimento);
        } catch (DAOException ex) {
            Logger.getLogger(FatMB.class.getName()).log(Level.SEVERE, "Erro ao gerarBoletos", ex);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Ocorreu um erro ao gerar os boletos!", null));
            return "falha";
        }
        return "sucesso";
    }
}

src/java/org/abepomi/mb/UserMB.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.abepomi.mb;

import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.abepomi.dao.DAOFactory;
import org.abepomi.dao.UserDAO;
import org.abepomi.dao.commons.DAOException;
//import org.abepomi.mb.util.GeraMd5;
import org.abepomi.mb.util.GeraMd5;
import org.abepomi.model.Pagina;
import org.abepomi.model.User;

/**
 *
 * @author Julianno
 */
public class UserMB implements Serializable {

    private User user = new User();
    private User novoUser = new User();
    private UserDAO userDAO = DAOFactory.createUserDAO();
    private List<User> usuarios = new ArrayList<User>();
    private String busca = "";
    private String senha = "";
    private boolean alterando = false;

    public UserMB() {
    }

    public boolean isAlterando() {
        return alterando;
    }

    public boolean isListaUsuariosVazia() {
        return (usuarios.size() > 0);
    }

    public void setAlterando(boolean alterando) {
        this.alterando = alterando;
    }

    public String getBusca() {
        return busca;
    }

    public void setBusca(String busca) {
        this.busca = busca;
    }

    public List<User> getUsuarios() {
        return usuarios;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User currentUser) {
        this.user = currentUser;
    }

    public User getNovoUser() {
        return novoUser;
    }

    public void setNovoUser(User novoUser) {
        this.novoUser = novoUser;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public List<Pagina> getPaginasUser() {
        List<Pagina> paginas;
        paginas = novoUser.getPaginas();
        novoUser.setPaginas(null);
        return paginas;
    }

    public void setPaginasUser(List<Pagina> paginas) {
        novoUser.setPaginas(paginas);
    }

    public String salvar() {
        //UserDAO userDAO = DAOFactory.createUserDAO();
        try {
            novoUser.getPaginas().addAll(DAOFactory.createPaginaDAO().getPaginasLiberadas());
            if (isAlterando()) {
                //novoUser.setSenha(md5(novoUser.getSenha()));
                userDAO.updateEntity(novoUser);
            } else {
                novoUser.setSenha(GeraMd5.md5(novoUser.getLogin()));
                userDAO.addEntity(novoUser);
            }
            setAlterando(false);
            novoUser = new User();
        } catch (NoSuchAlgorithmException nsa) {
            Logger.getLogger(UserMB.class.getName()).log(Level.SEVERE, "Erro ao salvar usuário!", nsa);
            return "falha";
        } catch (UnsupportedEncodingException uee) {
            Logger.getLogger(UserMB.class.getName()).log(Level.SEVERE, "Erro ao salvar usuário!", uee);
            return "falha";
        } catch (DAOException ex) {
            Logger.getLogger(UserMB.class.getName()).log(Level.SEVERE, "Erro ao salvar usuário!", ex);
            return "falha";
        }
        return "sucesso";
    }

    public String login() {
        User other = null;
        //UserDAO userDAO = DAOFactory.createUserDAO();
        try {
            other = userDAO.findById(user.getLogin());
        } catch (DAOException ex) {
            Logger.getLogger(UserMB.class.getName()).log(Level.SEVERE, "Erro ao logar", ex);
        }

        if (null == other) {
            FacesContext.getCurrentInstance().addMessage("principal", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Usuário não existe!!!", ""));
            return "loginPage";
        }

        try {
            if (!(GeraMd5.md5(user.getSenha()).equals(other.getSenha()))) {
                FacesContext.getCurrentInstance().addMessage("principal", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Usuário e/ou senha não conferem!!!", ""));
                return "loginPage";
            }
        } catch (NoSuchAlgorithmException nsa) {
            Logger.getLogger(UserMB.class.getName()).log(Level.SEVERE, "Erro ao salvar usuário!", nsa);
            return "falha";
        } catch (UnsupportedEncodingException uee) {
            Logger.getLogger(UserMB.class.getName()).log(Level.SEVERE, "Erro ao salvar usuário!", uee);
            return "falha";
        }

        FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("currentUser", other);

        if (user.getSenha().equals(user.getLogin())) {
            return "alterarSenha";
        }

        /*
        EmailAbepomi email = new EmailAbepomi();
        email.sendMail("juliannoms@gmail.com", "Logon de usuário!", "O usuário '"+other.getLogin()+"' entrou no sistema!\nNome: "+other.getNome()+".\nData: "+new Date()+".");
         */
        return "index";
    }

    public String logout() {
        FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("currentUser", null);
        return "loginPage";
    }

    public String selecionar() {
        /*try {
        novoUser = userDAO.findById(novoUser.getLogin());
        } catch (DAOException ex) {
        Logger.getLogger(UserMB.class.getName()).log(Level.SEVERE, "Erro ao selecionar usuário!", ex);
        }*/
        //novoUser.setPaginas(null);
        setAlterando(true);
        return "cadastroUsuario";
    }

    public String buscar() {
        usuarios = userDAO.buscarPorLogin(busca);
        return "pesquisaUsuario";
    }

    public String limpar() {
        novoUser = new User();
        setAlterando(false);
        return "cadastroUsuario";
    }

    public String alterarSenha() {
        if (user.getSenha().equals(senha)) {
            user = (User) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("currentUser");
            try {
                user.setSenha(GeraMd5.md5(senha));
            } catch (NoSuchAlgorithmException nsa) {
                Logger.getLogger(UserMB.class.getName()).log(Level.SEVERE, "Erro ao salvar usuário!", nsa);
                return "falha";
            } catch (UnsupportedEncodingException uee) {
                Logger.getLogger(UserMB.class.getName()).log(Level.SEVERE, "Erro ao salvar usuário!", uee);
                return "falha";
            }
            try {
                userDAO.updateEntity(user);
            } catch (DAOException ex) {
                FacesContext.getCurrentInstance().addMessage("principal", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Erro ao alterar senha!", ""));
                return "loginPage";
            }
        } else {
            FacesContext.getCurrentInstance().addMessage("principal", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Senha e confirmação não confere!", ""));
            return "alterarSenha";
        }

        return "index";

    }
}

web/associacao/boleto.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./../template/template.xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core">

    <ui:define name="head">
    </ui:define>

    <ui:define name="titulo">
        ABEPOMI - Emissão de Boleto
    </ui:define>

    <ui:define name="divTitulo">
        Emissão de Boleto
    </ui:define>

    <ui:define name="divCentro">
        <h:form id="formCentral" >
            <fieldset id="geral" class="geral">
                <fieldset id="interno" class="interno">
                    <legend>Dados</legend>
                    <label id="lass" for="ass">Associado:*</label>
                    <h:selectOneMenu id="ass"
                                     required="true"
                                     requiredMessage="Selecione um associado!"
                                     value="#{cobraMB.associado}">
                        <f:converter converterId="AssConverter" />
                        <f:selectItem itemLabel="Selecione" />
                        <f:selectItems value="#{cobraMB.associadosBoletos}"
                                       var="ass"
                                       itemLabel="#{ass.nome}" />
                    </h:selectOneMenu>
                    <h:message id="mass" for="ass" styleClass="errorMessage" />
                    <br />
                    <label id="lref" for="ref">Referência:*</label>
                    <h:selectOneMenu id="ref"
                                     required="true"
                                     requiredMessage="Selecione uma refência!"
                                     value="#{cobraMB.referencia}">
                        <f:converter converterId="RefConverter" />
                        <f:selectItem itemLabel="Selecione" />
                        <f:selectItems value="#{cobraMB.referencias}"
                                       var="ref"
                                       itemLabel="#{ref.ref}" />
                    </h:selectOneMenu>
                    <h:message id="mref" for="ref" styleClass="errorMessage" />
                    <br />
                    <h:commandButton action="#{cobraMB.gerarBoleto}"
                                     id="btnBoleto"
                                     value="Gerar Boleto" />

                </fieldset>
            </fieldset>
        </h:form>
    </ui:define>

</ui:composition>

web/associacao/boletos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition template="/template/template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets">



    <ui:define name="titulo">ABEPOMI - Gerar Boletos</ui:define>
    <ui:define name="divTopo"></ui:define>
    <ui:define name="divTitulo">Gerar Boletos</ui:define>
    <ui:define name="divCentro">
        <f:view>
            <h:form id="formCadastro">

                <fieldset class="geral">
                    <fieldset class="interno">
                        <legend>Dados</legend>
                        <label id="lref" for="ref">Referência:*</label>
                        <h:selectOneMenu id="ref" value="#{fatBean.referencia}" required="true" requiredMessage="Selecione uma referência!" >
                            <f:converter converterId="RefConverter" />
                            <f:selectItem itemLabel="Selecione" />
                            <f:selectItems value="#{fatBean.todasReferencias}" var="referencia" itemLabel="#{referencia.ref}" />
                        </h:selectOneMenu>
                        <h:message for="ref" styleClass="errorMessage" />
                        <br />
                        <label id="lvenc" for="venc">Déb. Aut.?</label>
                        <h:selectBooleanCheckbox id="nDebitados" value="#{fatBean.naoDebitados}" />
                        <br />
                        <label id="lvenc" for="venc">Vencimento:*</label>
                        <h:inputText id="venc"
                                     value="#{fatBean.vencimento}"
                                     required="true"
                                     requiredMessage="Informe a data de vencimento!"
                                     alt="date"
                                     styleClass="in160">
                            <f:converter converterId="DataConverter"/>
                        </h:inputText>
                        <h:message id="mvenc" for="venc" styleClass="errorMessage" />
                        <br />
                    </fieldset>
                    <h:commandButton id="btnsalvar" value="Gerar Boletos" action="#{fatBean.gerarBoletos}"/>
                    <h:commandButton id="btnsair" value="Sair" action="index" immediate="true" />
                </fieldset>
            </h:form>
        </f:view>
    </ui:define>
</ui:composition>

web/associacao/cadastrousuario.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./../template/template.xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html">

    <ui:define name="head">
    </ui:define>

    <ui:define name="titulo">
        ABEPOMI - Cadastro de Usuários
    </ui:define>

    <ui:define name="divTitulo">
        Cadastro de Usuários
    </ui:define>

    <ui:define name="divCentro">
        <f:view>
            <h:form id="formCadastro" >

                <fieldset class="geral">
                    <fieldset class="interno">
                        <legend>Dados do Usuário</legend>
                        <label id="luser" for="user">Login:*</label>
                        <h:inputText id="user" value="#{userBean.novoUser.login}"
                                     required="true" requiredMessage="Digite o login!"
                                     validatorMessage="O login deve ter no mínimo 6 e no máximo 20 caracteres!"
                                     onchange="this.value = this.value.toLowerCase();"
                                     readonly="#{userBean.alterando}">
                            <f:validateLength maximum="20" minimum="6"/>
                        </h:inputText>
                        <h:message id="muser" for="user" styleClass="errorMessage" />
                        <label id="lnome" for="nome">Nome:*</label>
                        <h:inputText id="nome" value="#{userBean.novoUser.nome}"
                                     required="true" requiredMessage="Digite o Nome!"
                                     validatorMessage="O login deve ter no máximo 50 caracteres!"
                                     onchange="this.value = this.value.toUpperCase();">
                            <f:validateLength maximum="50"/>
                        </h:inputText>
                        <h:message id="mnome" for="nome" styleClass="errorMessage" />
                        <br />
                    </fieldset>
                    <fieldset class ="interno" >
                        <legend>Páginas Autorizadas</legend>
                        <h:selectManyCheckbox id="autorizadas" value="#{userBean.paginasUser}" 
                                              layout="pageDirection"
                                              styleClass="paginasAutorizadas">
                            <f:selectItems id="paginas" 
                                           value="#{pageBean.paginasSeguras}"
                                           var="page"
                                           itemLabel="#{page.descricao}"
                                           itemValue="#{page}" >
                            </f:selectItems>
                            <f:converter converterId="PageConverter"  />
                        </h:selectManyCheckbox>
                    </fieldset>
                    <h:commandButton id="salvar" action="#{userBean.salvar}" value="Salvar" />
                    <h:commandButton id="pesquisar" action="pesquisaUsuario" value="Pesquisar" immediate="true"/>
                    <h:commandButton id="limpar" action="#{userBean.limpar}" value="Limpar" immediate="true"/>
                </fieldset>
            </h:form>
        </f:view>
    </ui:define>

</ui:composition>

web/associacao/extras.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition template="/template/template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets">


    <ui:define name="titulo">ABEPOMI - Lançamentos Extras</ui:define>
    <ui:define name="divTopo"></ui:define>
    <ui:define name="divTitulo">Lançamentos Extras</ui:define>
    <ui:define name="divCentro">
        <f:view>
            <h:form id="formExtras" >
                <fieldset class="geral">
                    <fieldset class="interno">
                        <legend>Dados</legend>
                        <label id="lref" for="ref">Referência:</label>
                        <h:selectOneMenu id="ref" value="#{fatBean.extra.referencia}" required="true" requiredMessage="Selecione uma referência!" >
                            <f:converter converterId="RefConverter" />
                            <f:selectItem itemLabel="Selecione" />
                            <f:selectItems value="#{fatBean.referencias}" var="referencia" itemLabel="#{referencia.ref}" />
                        </h:selectOneMenu>
                        <h:message for="ref" styleClass="errorMessage" />
                        <br />
                        <label id="lasso" for="asso">Associado:</label>
                        <h:inputText id="asso" value="#{associadoBean.associado.nome}" readonly="true" required="true" requiredMessage="Selecione um associado!" />
                        <h:message for="asso" styleClass="errorMessage" />
                        <h:commandLink value="Selecionar" action="#{associadoBean.pesquisarAssociado}" immediate="true">
                            <f:setPropertyActionListener value="extras" target="#{associadoBean.fromId}"/>
                        </h:commandLink>
                        <br />
                        <label id="ldesc" for="desc">Descrição:</label>
                        <h:inputText id="desc" value="#{fatBean.extra.descricao}" maxlength="50" required="true" 
                                     requiredMessage="Digite a descrição do lançamento!" onchange="this.value = this.value.toUpperCase()"/>
                        <h:message id="mdesc" for="desc" styleClass="errorMessage" />
                        <br />
                        <label id="lvalor" for="valor">Valor:</label>
                        <h:inputText id="valor" value="#{fatBean.extra.valor}" required="true" requiredMessage="Digite o valor do lançamento!" styleClass="in160" alt="decimal">
                            <f:convertNumber pattern="###0.00" />
                        </h:inputText>
                        <h:message id="mvalor" for="valor" styleClass="errorClass" />
                        <br />
                    </fieldset>
                    <h:commandButton id="btnsalvar" value="Salvar" action="#{fatBean.salvarExtra}">
                        <f:setPropertyActionListener target="#{fatBean.extra.associado}" value="#{associadoBean.associado}" />
                    </h:commandButton>
                    <h:commandButton id="btnsair" value="Sair" action="index" immediate="true" />
                </fieldset>
            </h:form>
        </f:view>
    </ui:define>
</ui:composition>