src/java/org/abepomi/mb/CobrancaMB.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.abepomi.mb;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.Serializable;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.validator.ValidatorException;
import javax.faces.component.UIComponent;
import javax.faces.application.FacesMessage;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.abepomi.arqs.cobranca.Retorno;
import org.abepomi.cobranca.CobrancaBB;
import org.abepomi.dao.DAOFactory;
import org.abepomi.dao.cobranca.TituloDAO;
import org.abepomi.dao.commons.DAOException;
import org.abepomi.exception.RetornoCobrancaInvalidoException;
import org.abepomi.mb.util.DownloadArq;
import org.abepomi.model.Associado;
import org.abepomi.model.Referencia;
import org.abepomi.model.cobranca.Header;
import org.abepomi.model.cobranca.Parcelamento;
import org.abepomi.model.cobranca.Registro;
import org.abepomi.model.cobranca.Titulo;

/**
 *
 * @author Julianno
 */
@ManagedBean(name = "cobraMB")
@ViewScoped
public class CobrancaMB implements Serializable {

    private static String LOCAL_ARQUIVO = "/upload/cobranca/";

    public CobrancaMB() {
        this.associados = DAOFactory.createTituloDAO().buscaAssPendente();
    }
    private Titulo titulo;
    private Associado associado;
    private List<Associado> associados;
    private List<Titulo> titulos;
    private Map<Integer, Boolean> checked = new HashMap<Integer, Boolean>();
    private BigDecimal total = new BigDecimal(0.00);
    private Integer parcelas = 1;
    private Boolean selecionado = false;
    private String arquivoSelecionado = "";
    //
    private Boolean baixaManual = false;
    private Integer motivoBaixa = null;
    private Date    dataBaixa   = new Date();
    //
    private List<Associado> associadosParcelamento = new ArrayList();

    private Referencia referencia;

    /**
     *  Getters and Setters
     */
    public List<Associado> getAssociados() {
        return associados;
    }

    public void setAssociados(List<Associado> associados) {
        this.associados = associados;
    }

    public List<Titulo> getTitulos() {
        return titulos;
    }

    public void setTitulos(List<Titulo> titulos) {
        this.titulos = titulos;
    }

    public Associado getAssociado() {
        return associado;
    }

    public void setAssociado(Associado associado) {
        this.associado = associado;
    }

    public Titulo getTitulo() {
        return titulo;
    }

    public void setTitulo(Titulo titulo) {
        this.titulo = titulo;
    }

    public Map<Integer, Boolean> getChecked() {
        return checked;
    }

    public void setChecked(Map<Integer, Boolean> checked) {
        this.checked = checked;
    }

    public BigDecimal getTotal() {
        return total;
    }

    public void setTotal(BigDecimal total) {
        //this.total = total;
    }

    public Integer getParcelas() {
        return parcelas;
    }

    public void setParcelas(Integer parcelas) {
        this.parcelas = parcelas;
    }

    public Boolean getSelecionado() {
        return selecionado;
    }

    public void setSelecionado(Boolean selecionado) {
        this.selecionado = selecionado;
    }

    public void setArquivoSelecionado(String arquivoSelecionado) {
        this.arquivoSelecionado = arquivoSelecionado;
    }

    public Referencia getReferencia() {
        return referencia;
    }

    public void setReferencia(Referencia referencia) {
        this.referencia = referencia;
    }

    public Boolean getBaixaManual() {
        return baixaManual;
    }

    public void setBaixaManual(Boolean baixaManual) {
        this.baixaManual = baixaManual;
    }

    public Date getDataBaixa() {
        return dataBaixa;
    }

    public void setDataBaixa(Date dataBaixa) {
        this.dataBaixa = dataBaixa;
    }

    public Integer getMotivoBaixa() {
        return motivoBaixa;
    }

    public void setMotivoBaixa(Integer motivoBaixa) {
        this.motivoBaixa = motivoBaixa;
    }

    public List<Associado> getAssociadosParcelamentos(){
        if(associadosParcelamento.isEmpty()){
            associadosParcelamento = DAOFactory.createParcelamentoDAO().buscarAssociadosParcelamento();
        }
        return associadosParcelamento;
    }
    
    public void carregarTitulosAssociados(ValueChangeEvent event) {
        if (event.getNewValue() != event.getOldValue()) {
            if (event.getNewValue() instanceof Associado) {
                titulos = DAOFactory.createTituloDAO().buscaPorAssEst((Associado) event.getNewValue(), 11);
                checked.clear();
                total = new BigDecimal(0.00);
                selecionado = false;
            }
            FacesContext.getCurrentInstance().renderResponse();
        }
    }

    public void carregarTitulosSelecionados(AjaxBehaviorEvent event) {
        total = new BigDecimal(0.00);
        for (Titulo t : titulos) {
            if (checked.containsKey(t.getId()) && checked.get(t.getId())) {
                total = total.add(t.getValor());
            }
        }
        FacesContext.getCurrentInstance().renderResponse();
    }

    public void selecionarTodos(AjaxBehaviorEvent event) {
        boolean ok = selecionado;
        total = new BigDecimal(0.00);
        for (Titulo t : titulos) {
            checked.put(t.getId(), ok);
            if (ok) {
                total = total.add(t.getValor());
            }
        }
        FacesContext.getCurrentInstance().renderResponse();
    }

    public void validarValor(FacesContext context, UIComponent component, Object value) {
        if (total.doubleValue() == 0.00) {
            throw new ValidatorException(new FacesMessage("Valor inválido! Selecione um débito!"));
        }

    }

    public String gerarParcelas() {
        List<Titulo> selecionados = new ArrayList<Titulo>();
        for (Titulo t : titulos) {
            if (checked.get(t.getId())) {
                selecionados.add(t);
            }
        }
        Parcelamento parcelamento = new Parcelamento();
        parcelamento.setQtde(parcelas);
        parcelamento.setTotal(total);
        parcelamento.setAssociado(associado);
        parcelamento.setTitulos(selecionados);
        parcelamento.gerarParcelas();
        try {
            DAOFactory.createParcelamentoDAO().addEntity(parcelamento);
            DAOFactory.createTituloDAO().atualizarTitulosNegociados(selecionados);
        } catch (DAOException daoex) {
            Logger.getLogger(CobrancaMB.class.getName()).log(Level.SEVERE, "Erro ao gravar parcelamento!", daoex);
            return "falha";
        }
        return "sucesso";
    }

    public List<String[]> getArquivos() {
        File[] files = new File(FacesContext.getCurrentInstance().getExternalContext().getRealPath("/upload/cobranca") + "/").listFiles();
        List<String[]> lista = new ArrayList<String[]>();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        for (File file : files) {
            String[] arq = {"", "", ""};
            arq[0] = file.getName();
            arq[1] = String.valueOf(sdf.format(new Date(file.lastModified())));
            arq[2] = String.valueOf(file.length()) + " bytes";
            lista.add(arq);
        }
        return lista;
    }

    public String getLocalArquivo(){
        return LOCAL_ARQUIVO;
    }

    public String salvarArquivo(){
        return "upload/uploadcobranca";
    }

    public String apagarArquivo() {
        String caminho = FacesContext.getCurrentInstance().getExternalContext().getRealPath("/upload/telefonia");
        File file = new File(caminho + "/" + arquivoSelecionado);
        if (file.delete()) {
            return "upload/uploadcobranca";
        }
        return "falha";
    }

    public String processarArquivo(){
        try {
            Header header = Retorno.processar(FacesContext.getCurrentInstance().getExternalContext().getRealPath(LOCAL_ARQUIVO)+"/"+arquivoSelecionado);
            int qtde = 0;
            if(!(null == header.getRegistros())){
                for(Registro r : header.getRegistros()){
                    qtde = qtde + DAOFactory.createTituloDAO().atualizaTituloRetorno(r.getCodMov(), r.getDtMovimento(), r.getValorPago(), r.getNossoNro());
                }
            }
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, qtde+" títulos atualizados!",null));
            return "sucesso";
        }  catch (RetornoCobrancaInvalidoException ex) {
            Logger.getLogger(CobrancaMB.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(),null));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CobrancaMB.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(),null));
        } catch (IOException ex) {
            Logger.getLogger(CobrancaMB.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);

web/upload/uploadcobranca.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./../template/template.xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ab="http://tag.abepomi.org/upload">

    <ui:define name="head"></ui:define>

    <ui:define name="titulo">
        ABEPOMI - Upload de Arquivos de Retorno de Cobrança
    </ui:define>

    <ui:define name="divTitulo">
        Upload de Arquivos de Retorno de Cobrança
    </ui:define>

    <ui:define name="divCentro">
<f:view>
            <fieldset id="principal" class="geral">
                <h:form id="formUpload" enctype="multipart/form-data">
                    <fieldset id="fieldUp" class="interno">
                        <ab:upload target="#{cobraMB.localArquivo}" id="file" />
                        <br />
                        <h:commandButton action="#{cobraMB.salvarArquivo}" value="Enviar" />
                    </fieldset>
                </h:form>
                <h:form id="arquivos">
                    <fieldset id="fieldArqs" class="interno">

                        <legend>Arquivos Enviados</legend>
                        <h:dataTable id="tabela" value="#{cobraMB.arquivos}" var="arq" rendered="#{!cobraMB.arquivos.isEmpty()}">
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerNome" value="Nome:" styleClass="head" />
                                </f:facet>
                                <h:outputText id="nome" value="#{arq[0]}" styleClass="column"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerData" value="Data:" styleClass="head" />
                                </f:facet>
                                <h:outputText id="data" value="#{arq[1]}" styleClass="column"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerTamanho" value="Tamanho:" styleClass="head" />
                                </f:facet>
                                <h:outputText id="tamanho" value="#{arq[2]}" styleClass="column"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerAcao" value="Ação:" styleClass="head" />
                                </f:facet>
                                <h:commandLink id="acaoProcessar" value="Processar" action="#{cobraMB.processarArquivo}" styleClass="column">
                                    <f:setPropertyActionListener target="#{cobraMB.arquivoSelecionado}" value="#{arq[0]}" />
                                </h:commandLink>/
                                <h:commandLink id="acaoApagar" value="Apagar" action="#{cobraMB.apagarArquivo}" styleClass="column">
                                    <f:setPropertyActionListener target="#{cobraMB.arquivoSelecionado}" value="#{arq[0]}" />
                                </h:commandLink>
                            </h:column>
                        </h:dataTable>
                        <h:outputText id="informe" styleClass="informe" value="Não há arquivos a serem mostrados!" rendered="#{cobraMB.arquivos.isEmpty()}"/>
                    </fieldset>
                </h:form>
            </fieldset>
        </f:view>
    </ui:define>

</ui:composition>

web/upload/uploaddebautomatico.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/template/template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:ab="http://tag.abepomi.org/upload">



    <ui:define name="titulo">ABEPOMI - Arquivos Débito Automático</ui:define>
    <ui:define name="divTopo"></ui:define>
    <ui:define name="divTitulo">Retorno Débito Automático</ui:define>
    <ui:define name="divCentro">
        <f:view>
            <fieldset id="principal" class="geral">
                <h:form id="formUpload" enctype="multipart/form-data">
                    <fieldset id="fieldUp" class="interno">
                        <ab:upload target="#{asoBean.arquivoDA}" id="file" />
                        <br />
                        <h:commandButton action="#{asoBean.salvarArquivo}" value="Enviar" />
                    </fieldset>
                </h:form>
                <h:form id="arquivos">
                    <fieldset id="fieldArqs" class="interno">

                        <legend>Arquivos Enviados</legend>
                        <h:dataTable id="tabela" value="#{asoBean.arquivosDA}" var="arq" rendered="#{!asoBean.arquivosDA.isEmpty()}">
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerNome" value="Nome:" styleClass="head" />
                                </f:facet>
                                <h:outputText id="nome" value="#{arq[0]}" styleClass="column"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerData" value="Data:" styleClass="head" />
                                </f:facet>
                                <h:outputText id="data" value="#{arq[1]}" styleClass="column"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerTamanho" value="Tamanho:" styleClass="head" />
                                </f:facet>
                                <h:outputText id="tamanho" value="#{arq[2]}" styleClass="column"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerAcao" value="Ação:" styleClass="head" />
                                </f:facet>
                                <h:commandLink id="acaoProcessar" value="Processar" action="#{asoBean.processarArquivoRetorno}" styleClass="columnr">
                                    <f:setPropertyActionListener target="#{asoBean.arquivo}" value="#{arq[0]}" />
                                </h:commandLink>/
                                <h:commandLink id="acaoApagar" value="Apagar" action="#{asoBean.apagarArqDA}" styleClass="column">
                                    <f:setPropertyActionListener target="#{asoBean.arquivo}" value="#{arq[0]}" />
                                </h:commandLink>
                            </h:column>
                        </h:dataTable>
                        <h:outputText id="informe" styleClass="informe" value="Não há arquivos a serem mostrados!" rendered="#{asoBean.arquivosDA.isEmpty()}"/>
                    </fieldset>
                </h:form>
            </fieldset>
        </f:view>
    </ui:define>
</ui:composition>

web/upload/uploadtelefonia.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./../template/template.xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ab="http://tag.abepomi.org/upload">
    
    <ui:define name="head"></ui:define>

    <ui:define name="titulo">
        ABEPOMI - Upload de Arquivos de Telefonia
    </ui:define>

    <ui:define name="divTitulo">
        Upload de Arquivos de Telefonia
    </ui:define>

    <ui:define name="divCentro">
<f:view>
            <fieldset id="principal" class="geral">
                <h:form id="formUpload" enctype="multipart/form-data">
                    <fieldset id="fieldUp" class="interno">
                        <ab:upload target="#{teleBean.localArquivo}" id="file" />
                        <br />
                        <h:commandButton action="#{teleBean.salvarArquivo}" value="Enviar" />
                    </fieldset>
                </h:form>
                <h:form id="arquivos">
                    <fieldset id="fieldArqs" class="interno">

                        <legend>Arquivos Enviados</legend>
                        <h:dataTable id="tabela" value="#{teleBean.arquivos}" var="arq" rendered="#{!teleBean.arquivos.isEmpty()}">
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerNome" value="Nome:" styleClass="head" />
                                </f:facet>
                                <h:outputText id="nome" value="#{arq[0]}" styleClass="column"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerData" value="Data:" styleClass="head" />
                                </f:facet>
                                <h:outputText id="data" value="#{arq[1]}" styleClass="column"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerTamanho" value="Tamanho:" styleClass="head" />
                                </f:facet>
                                <h:outputText id="tamanho" value="#{arq[2]}" styleClass="column"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerAcao" value="Ação:" styleClass="head" />
                                </f:facet>
                                <h:commandLink id="acaoProcessar" value="Processar" action="#{teleBean.processarArquivo}" styleClass="columnr">
                                    <f:setPropertyActionListener target="#{teleBean.arquivoSelecionado}" value="#{arq[0]}" />
                                </h:commandLink>/
                                <h:commandLink id="acaoApagar" value="Apagar" action="#{teleBean.apagarArquivo}" styleClass="column">
                                    <f:setPropertyActionListener target="#{teleBean.arquivoSelecionado}" value="#{arq[0]}" />
                                </h:commandLink>
                            </h:column>
                        </h:dataTable>
                        <h:outputText id="informe" styleClass="informe" value="Não há arquivos a serem mostrados!" rendered="#{teleBean.arquivos.isEmpty()}"/>
                    </fieldset>
                </h:form>
            </fieldset>
        </f:view>
    </ui:define>

</ui:composition>