src/java/org/abepomi/model/Aparelho.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.abepomi.model;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 *
 * @author Julianno
 */
@Entity
@Table(name = "aparelhos", schema = "public")
@SequenceGenerator(name = "seqaparelhos", sequenceName = "seq_aparelhos", allocationSize = 1)
@NamedQueries({
    @NamedQuery(name = "Aparelho.estoque", query = "select a from Aparelho a where a.estoque > 0 order by a.nome")
})
public class Aparelho implements Serializable {

    @Id
    @GeneratedValue(generator = "seqaparelhos", strategy = GenerationType.SEQUENCE)
    private int id;
    @Column(name = "nome", length = 50)
    private String nome = null;
    @Column(name = "estoque")
    private int estoque = 0;
    @Column(name = "preco_medio")
    private Double valorMedio = null;
    @Column(name = "preco_venda")
    private Double valorVenda = null;

    public Aparelho() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public int getEstoque() {
        return estoque;
    }

    public void setEstoque(int estoque) {
        this.estoque = estoque;
    }

    public Double getValorMedio() {
        return valorMedio;
    }

    public void setValorMedio(Double valorMedio) {
        this.valorMedio = valorMedio;
    }

    public Double getValorVenda() {
        return valorVenda;
    }

    public void setValorVenda(Double valorVenda) {
        this.valorVenda = valorVenda;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Aparelho other = (Aparelho) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + this.id;
        return hash;
    }

    @Override
    public String toString() {
        return "org.abepomi.model.Aparelho{" + "id=" + id + "nome=" + nome + "estoque=" + estoque + "valorMedio=" + valorMedio + "valorVenda=" + valorVenda + '}';
    }
}

src/java/org/abepomi/model/NotaFiscal.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.abepomi.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.abepomi.model.util.OperacaoNota;

/**
 *
 * @author Julianno
 */
@Entity
@Table(name="notafiscal", schema="public")
@SequenceGenerator(name="seqnotafiscal", sequenceName="seq_notafiscal", allocationSize=1)
public class NotaFiscal implements Serializable{

    @Id
    @GeneratedValue(generator="seqnotafiscal", strategy=GenerationType.SEQUENCE)
    private int id;

    @Temporal(TemporalType.DATE)
    @Column(name="data")
    private Date data;

    @Column(name="numero", length=15)
    private String numero;

    @Column(name="valor")
    private Double valor = 0.00;

    @Enumerated(EnumType.STRING)
    @Column(name="operacao", length=1)
    private OperacaoNota operacao;

    @ManyToOne(fetch=FetchType.EAGER, cascade=CascadeType.ALL)
    @JoinColumn(name="for_id", referencedColumnName="id")
    private Fornecedor fornecedor = new Fornecedor();

    @OneToMany(fetch=FetchType.LAZY, cascade=CascadeType.ALL, mappedBy="notaFiscal")
    private List<ItensNota> itens = new ArrayList<ItensNota>();

    

    public NotaFiscal() {
    }

    public Date getData() {
        return data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    public Fornecedor getFornecedor() {
        return fornecedor;
    }

    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNumero() {
        return numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public Double getValor() {
        return valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    public OperacaoNota getOperacao() {
        return operacao;
    }

    public void setOperacao(OperacaoNota operacao) {
        this.operacao = operacao;
    }

    public List<ItensNota> getItens() {
        return itens;
    }

    public void setItens(List<ItensNota> itens) {
        this.itens = itens;
    }

    

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final NotaFiscal other = (NotaFiscal) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 61 * hash + this.id;
        return hash;
    }

    @Override
    public String toString() {
        return "org.abepomi.model.NotaFiscal{" + "id=" + id + "data=" + data + "numero=" + numero + "valor=" + valor + "operacao=" + operacao + "fornecedor=" + fornecedor + '}';
    }



}

src/java/org/abepomi/mb/AssociadoMB.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.abepomi.mb;

import java.io.ByteArrayOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import org.abepomi.model.util.Estados;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.context.FacesContext;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.abepomi.arqs.ArqEmails;
import org.abepomi.cobranca.CobrancaBB;
import org.abepomi.dao.AssDADAO;
import org.abepomi.dao.AssociadoDAO;
import org.abepomi.dao.DAOFactory;
import org.abepomi.dao.VeiculoDAO;
import org.abepomi.dao.commons.DAOException;
import org.abepomi.dao.util.AssociadoEmail;
import org.abepomi.dao.util.AssociadoLinhaUtilRel;
import org.abepomi.dao.util.DetalheTelefoniaUtilRel;
import org.abepomi.dao.util.FaturaUtilRelCusto;
import org.abepomi.dao.util.FaturamentoRefRel;
import org.abepomi.dao.util.RefVivoRel;
import org.abepomi.mail.EmailAbepomi;
import org.abepomi.mail.EmailMensalThread;
import org.abepomi.mb.util.DownloadArq;
import org.abepomi.mb.util.GeraMd5;
import org.abepomi.model.AssDA;
import org.abepomi.model.Associado;
import org.abepomi.model.ConvDA;
import org.abepomi.model.Dependente;
import org.abepomi.model.Faturamento;
import org.abepomi.model.Linha;
import org.abepomi.model.MovDA;
import org.abepomi.model.Referencia;
import org.abepomi.model.Veiculo;
import org.abepomi.model.cobranca.Titulo;
import org.abepomi.model.util.Categoria;
import org.abepomi.model.util.EstadoDA;
import org.abepomi.model.util.EstadosCivil;
import org.abepomi.model.util.Pagto;
import org.abepomi.model.util.Parentesco;
import org.abepomi.model.util.Sexo;
import org.abepomi.model.util.Status;
import org.abepomi.model.util.Validacao;
import org.abepomi.pdf.PdfUtil;

/**
 *
 * @author Julianno
 */
public class AssociadoMB implements Serializable {

    public AssociadoMB() {
        associado = new Associado();
        dependente = new Dependente();
        veiculo = new Veiculo();

        /*
        AssociadoLinhaUtil assLU = new AssociadoLinhaUtil(1, "", new GregorianCalendar(2011, 04, 25).getTime(), new GregorianCalendar(2012, 02, 19).getTime(), 0);
        assLU.calculaProporcao(new GregorianCalendar(2012, 01, 20).getTime(), new GregorianCalendar(2012, 02, 19).getTime());
         */
    }
    private Associado associado;
    private Dependente dependente;
    private Veiculo veiculo;
    private AssDA assDA = null;
    private List<Associado> associados;
    private int selecionado;
    private String fromId;
    private String filtro;
    private String busca;
    private static AssociadoDAO assDAO = DAOFactory.createAssociadoDAO();
    //private static DependenteDAO depDAO = DAOFactory.createDependenteDAO();
    private static VeiculoDAO veiDAO = DAOFactory.createVeiculoDAO();
    private static AssDADAO daDAO = DAOFactory.createAssDADAO();
    private Referencia referencia;
    private String relNome = "";
    private Date dataInicio = null;

    public Date getDataInicio() {
        return dataInicio;
    }

    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    public List<Date> getDatasInicio() {
        if (fromId.equals("relFaturaTelefonica")) {
            Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "entrou no relFaturaTelefonica");
            return DAOFactory.createFaturaDAO().buscarDatasInicio();
        } else if (fromId.equals("relFatVivo")) {
            Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "relFatVivo");
            return DAOFactory.createFaturaVivoDAO().buscarFaturas();
        }
        Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "relFatVivoTelefonicaNULO");
        return null;
    }

    public String getRelNome() {
        return relNome;
    }

    public void setRelNome(String relNome) {
        this.relNome = relNome;
    }

    public String salvar() throws DAOException {
        String retorno = "falha";
        //try {
        try {
            if (associado.getId() == 0) {
                assDAO.addEntity(associado);
                cadastrarDA();
            } else {
                assDAO.updateEntity(associado);
            }
            retorno = "sucesso";
        } catch (DAOException ex) {
            Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "Erro: salvar()", ex);
        }
        //} finally {
        associado = new Associado();
        return retorno;
        //}



    }

    public AssDA getAssDA() {
        return assDA;
    }

    public void setAssDA(AssDA assDA) {
        this.assDA = assDA;
    }

    public Referencia getReferencia() {
        return referencia;
    }

    public void setReferencia(Referencia referencia) {
        this.referencia = referencia;
    }

    public Associado getAssociado() {
        return associado;
    }

    public void setAssociado(Associado associado) {
        this.associado = associado;
    }

    public List<Associado> getAssociados() {
        return associados;
    }

    public void setAssociados(List<Associado> associados) {
        this.associados = associados;
    }

    public String buscarAssociado() {
        try {
            if (filtro.equals("nome")) {
                associados = assDAO.buscaPorNome(busca);
            } else if (filtro.equals("cpf")) {
                associados = assDAO.buscaPorCpf(busca);
            }
        } catch (DAOException ex) {
            Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "Erro: buscarAssociado()", ex);
        }

        busca = "";
        return "pesquisar";
    }

    public String buscarTodosAssociados() {
        try {
            associados = assDAO.findAllByNome();
        } catch (DAOException ex) {
            Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "Erro: buscarTodosAssociados()", ex);
        }

        return "pesquisar";

    }

    public void setFiltro(String filtro) {
        this.filtro = filtro;
    }

    public String getFiltro() {
        return filtro;
    }

    public String getBusca() {
        return busca;
    }

    public void setBusca(String busca) {
        this.busca = busca;
    }

    public int getSelecionado() {
        return selecionado;
    }

    public void setSelecionado(int selecionado) {
        this.selecionado = selecionado;
    }

    public String selecionarAssociado() {
        try {
            associado = assDAO.findById(selecionado);
            assDA = daDAO.buscaPorAssociado(associado);
        } catch (DAOException ex) {
            Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "Erro: selecionarAssociado()", ex);
        }
        return fromId;
    }

    public String pesquisarAssociado() {
        return "pesquisar";
    }

    public String cancelar() {
        associado = new Associado();
        dependente = new Dependente();
        return "cadastro";
    }

    public Map getEstados() {
        Map<Estados, String> est = new LinkedHashMap<Estados, String>();
        for (Estados type : Estados.values()) {
            est.put(type, type.name());
        }
        return est;
    }

    public Map getParentesco() {
        Map<Parentesco, String> par = new LinkedHashMap<Parentesco, String>();
        for (Parentesco type : Parentesco.values()) {
            par.put(type, type.name());
        }
        return par;
    }

    public Map getCivil() {
        Map<EstadosCivil, String> est = new LinkedHashMap<EstadosCivil, String>();
        for (EstadosCivil type : EstadosCivil.values()) {
            est.put(type, type.name());
        }
        return est;
    }

    public Map getSexo() {
        Map<Sexo, String> sexo = new LinkedHashMap<Sexo, String>();
        for (Sexo type : Sexo.values()) {
            sexo.put(type, type.name());
        }
        return sexo;
    }

    public Map getPagto() {
        Map<Pagto, String> pagto = new LinkedHashMap<Pagto, String>();
        for (Pagto type : Pagto.values()) {
            pagto.put(type, type.name());
        }
        return pagto;
    }

    public Map getCategoria() {
        Map<Categoria, String> categoria = new LinkedHashMap<Categoria, String>();
        for (Categoria type : Categoria.values()) {
            categoria.put(type, type.name());
        }
        return categoria;
    }

    public Dependente getDependente() {
        return dependente;
    }

    public void setDependente(Dependente dependente) {
        this.dependente = dependente;
    }

    public String salvarDependente() {

        if (dependente.getId() == 0) {
            associado.getDependentes().add(dependente);
            dependente.setAssociado(associado);
        }
        try {
            assDAO.updateEntity(associado);
            associado = assDAO.findById(associado.getId());
        } catch (DAOException ex) {
            Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "Erro: salvarDependente()", ex);
        }



        dependente = new Dependente();

        return "dependentes";
    }

    public String alterarDependente() {
        return "dependentes";
    }

    public String excluirDependente() {
        /*associado.getDependentes().remove(dependente);
        dependente.setAssociado(null);
        try {
        assDAO.updateEntity(associado);
        depDAO.updateEntity(dependente);
        depDAO.removeEntity(dependente);
        } catch (DAOException ex) {
        Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, null, ex);
        }

web/notafiscal/aparelhos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./../template/template.xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html">

    <ui:define name="head"></ui:define>

    <ui:define name="titulo">
        ABEPOMI - Cadastro de Aparelhos
    </ui:define>

    <ui:define name="divTitulo">
        Cadastro de Aparelhos
    </ui:define>

    <ui:define name="divCentro">
        <f:view>
            <h:form>
                <fieldset class="geral">
                    <fieldset class="interno">
                        <legend>Aparelho</legend>
                        <h:inputHidden id="id" value="#{fornMB.aparelho.id}" />
                        <label id="lnome" for="nome">Nome:*</label>
                        <h:inputText value="#{fornMB.aparelho.nome}"
                                     id="nome"
                                     required="true"
                                     requiredMessage="Digite o nome!"
                                     validatorMessage="Nome do aparelho maior que 50 caracteres!"
                                     onchange="this.value = this.value.toUpperCase();">
                            <f:validateLength for="nome" maximum="50" />
                        </h:inputText>
                        <h:message id="mnome" for="nome" errorClass="errorMessage" />
                        <br />
                        <label id="lvenda" for="venda">Venda R$:*</label>
                        <h:inputText value="#{fornMB.aparelho.valorVenda}"
                                     id="venda"
                                     required="true"
                                     requiredMessage="Digite o valor de venda!"
                                     converterMessage="Valor inválido!"
                                     validatorMessage="Valor deve ser maior que 0,00!"
                                     styleClass="in160"
                                     alt="decimal">
                            <f:convertNumber pattern="###0.00" />
                            <f:validateDoubleRange minimum="0.01" />
                        </h:inputText>
                        <h:message id="mvenda" for="venda" errorClass="errorMessage" />
                        <br />
                        <label id="lmedio" for="medio">Valor médio:</label>
                        <h:inputText value="#{fornMB.aparelho.valorMedio}"
                                     id="medio"
                                     readonly="true"
                                     styleClass="in160"
                                     alt="decimal">
                            <f:convertNumber pattern="###0.00" />
                        </h:inputText>
                        <br />
                        <label id="lestoque" for="estoque">Estoque:</label>
                        <h:inputText value="#{fornMB.aparelho.estoque}"
                                     id="estoque"
                                     readonly="true"
                                     styleClass="in160"
                                     alt="decimal">
                            <f:convertNumber pattern="###0.00" />
                        </h:inputText>
                        <br />
                        <h:selectBooleanCheckbox id="mostrarAparelhos"
                                                 value="#{fornMB.mostrarAparelhos}">
                            <f:ajax event="valueChange"
                                    execute="@this"
                                    render="grpAparelhos"/>
                        </h:selectBooleanCheckbox>
                        <br />
                        <h:panelGroup id="grpAparelhos">
                            <h:dataTable id="tabelaAparelhos" value="#{fornMB.aparelhos}" var="apSel" rendered="#{fornMB.mostrarAparelhos}">
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerId" value="Id.:" />
                                </f:facet>
                                <h:outputText id="valueId" value="#{apSel.id}" />
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerNome" value="Nome:" />
                                </f:facet>
                                <h:outputText id="valueNome" value="#{apSel.nome}" />
                            </h:column>
                            <h:column >
                                <f:facet name="header">
                                    <h:outputText id="headerVenda" value="Valor de venda:"  />
                                </f:facet>
                                <h:outputText id="valueVenda" value="#{apSel.valorVenda}" />
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerSelecione" value="Selecione:" />
                                </f:facet>
                                <h:commandLink action="#{fornMB.carregarAlteracao}" value="Alterar" immediate="true">
                                    <f:setPropertyActionListener value="#{apSel}" target="#{fornMB.aparelho}" />
                                </h:commandLink>
                            </h:column>
                        </h:dataTable>
                        </h:panelGroup>
                    </fieldset>
                    <h:commandButton id="salvar" action="#{fornMB.salvarAparelho}" value="Salvar" />
                    <h:commandButton id="limpar" action="#{fornMB.limparAparelho}" value="Limpar" immediate="true" />

                </fieldset>
            </h:form>
        </f:view>
    </ui:define>

</ui:composition>

web/notafiscal/fornecedores.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./../template/template.xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html">
    
    <ui:define name="head"></ui:define>

    <ui:define name="titulo">
        ABEPOMI - Cadastro de Fornecedores
    </ui:define>

    <ui:define name="divTitulo">
        Cadastro de Fornecedores
    </ui:define>

    <ui:define name="divCentro">
        <f:view>
            <h:form>
                <fieldset class="geral">
                    <fieldset class="interno">
                        <legend>Fornecedor</legend>
                        <h:inputHidden id="id" value="#{fornMB.fornecedor.id}" />
                        <label id="lrazao" for="razao">Razão Social:*</label>
                        <h:inputText id="razao"
                                     value="#{fornMB.fornecedor.nome}"
                                     required="true"
                                     requiredMessage="Digite a razão social!"
                                     onchange="this.value = this.value.toUpperCase();"
                                     validatorMessage="Razão social maior que 50 caracteres!">
                            <f:validateLength maximum="50"/>
                        </h:inputText>
                        <h:message id="mrazao"
                                   for="razao"
                                   styleClass="errorMessage" />
                        <br />
                        <label id="lie" for="ie">I. E.:*</label>
                        <h:inputText id="ie"
                                     value="#{fornMB.fornecedor.rgie}"
                                     required="true"
                                     requiredMessage="Digite a inscrição estadual!"
                                     onchange="this.value = this.value.toUpperCase();"
                                     validatorMessage="Razão social maior que 14 caracteres!">
                            <f:validateLength maximum="14"/>
                        </h:inputText>
                        <h:message id="mie"
                                   for="ie"
                                   styleClass="errorMessage" />
                        <br />
                        <label id="lcnpj" for="cnpj">CNPJ:*</label>
                        <h:inputText id="cnpj"
                                     value="#{fornMB.fornecedor.cpfcnpj}"
                                     required="true"
                                     requiredMessage="Digite o CNPJ!"
                                     alt="cnpj">
                            <f:validator validatorId="ValidaCpfCnpj"  />
                            <f:converter converterId="RetiraMascaraString" />
                        </h:inputText>
                        <h:message id="mcnpj"
                                   for="cnpj"
                                   styleClass="errorMessage" />
                        <br />
                        <label id="lcontato" for="contato">Contato:</label>
                        <h:inputText id="contato"
                                     value="#{fornMB.fornecedor.contato}"
                                     validatorMessage="Nome do contato maior que 50 caracteres!"
                                     onchange="this.value = this.value.toUpperCase();">
                            <f:validateLength maximum="50"/>
                        </h:inputText>
                        <br />
                        <label id="ltel" for="tel">Telefone:</label>
                        <h:inputText id="tel"
                                     value="#{fornMB.fornecedor.telefone}"
                                     alt="phone">
                            <f:converter converterId="RetiraMascaraString" />
                        </h:inputText>
                        <br />
                    </fieldset>
                    <fieldset class="interno">
                        <legend>Endereço</legend>
                        <label id="llogradouro" for="ilogradouro">Logradouro:</label>
                        <h:inputText id="ilogradouro"
                                     value="#{fornMB.fornecedor.endereco.logradouro}"
                                     onchange="this.value = this.value.toUpperCase();"
                                     validatorMessage="Logradouro maior que 50 caracteres!">
                            <f:validateLength maximum="50"/>
                        </h:inputText>
                        <h:message id="mlogradouro" for="ilogradouro" styleClass="errorMessage" />
                        <br />
                        <label id="lcidade" for="icidade">Cidade:</label>
                        <h:inputText id="icidade"
                                     value="#{fornMB.fornecedor.endereco.cidade}"
                                     onchange="this.value = this.value.toUpperCase();"
                                     validatorMessage="Cidade maior que 50 caracteres!">
                            <f:validateLength maximum="50"/>
                        </h:inputText>
                        <h:message id="mcidade" for="icidade" styleClass="errorMessage" />
                        <br />
                        <label id="luf" for="iuf">Estado:</label>
                        <h:selectOneMenu id="iuf"
                                         value="#{fornMB.fornecedor.endereco.uf}">
                            <f:selectItem itemLabel="Selecione" />
                            <f:selectItems value="#{associadoBean.estados}" />
                        </h:selectOneMenu>
                        <h:message for="iuf" styleClass="errorMessage" />
                        <br />
                        <label id="lcep" for="icep">CEP:</label>
                        <h:inputText id="icep" 
                                     value="#{fornMB.fornecedor.endereco.cep}"
                                     styleClass="in160" alt="cep">
                            <f:converter converterId="RetiraMascaraString" />
                        </h:inputText>
                        <h:message id="mcep" for="icep" styleClass="errorMessage"/>
                        <br />
                    </fieldset>
                    <h:commandButton action="#{fornMB.salvarFornecedor}" 
                                     value="Salvar"
                                     id="btnSalvar" />
                </fieldset>
            </h:form>
        </f:view>
    </ui:define>

</ui:composition>