src/java/org/abepomi/model/Associacao.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.abepomi.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 *
 * @author Julianno
 */

@Entity
@SequenceGenerator(name="seqaso", sequenceName="seq_associacao", allocationSize=1)
@Table(name="associacao", schema="public")
public class Associacao implements Serializable {

    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="seqaso")
    private int id;

    @Column(name="nome", length=50)
    private String nome;

    @Column(name="cnpj", length=14)
    private String cnpj;

    @Column(name="ie", length=14)
    private String ie;

    @Column(name="telefone", length=10)
    private String telefone;

    @Column(name="contato", length=50)
    private String contato;

    @Column(name="uc", precision=10, scale=2)
    private Double unContribuicao;

    @Column(name="mult", precision=10, scale=2)
    private Double multContribuicao;

    @OneToOne(cascade=CascadeType.ALL, fetch=FetchType.EAGER)
    @JoinColumn(name="endereco", referencedColumnName="id")
    private Endereco endereco = new Endereco();

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="associacao")
    private List<ConvDA> conveniosDA = new ArrayList<ConvDA>();

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="associacao")
    private List<Fornecedor> fornecedores = new ArrayList<Fornecedor>();

    public Associacao() {
    }

    public Double getMultContribuicao() {
        return multContribuicao;
    }

    public void setMultContribuicao(Double multContribuicao) {
        this.multContribuicao = multContribuicao;
    }

    public List<Fornecedor> getFornecedores() {
        return fornecedores;
    }

    public void setFornecedores(List<Fornecedor> fornecedores) {
        this.fornecedores = fornecedores;
    }

    public List<ConvDA> getConveniosDA() {
        return conveniosDA;
    }

    public void setConveniosDA(List<ConvDA> conveniosDA) {
        this.conveniosDA = conveniosDA;
    }



    public String getCnpj() {
        return cnpj;
    }

    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    public String getContato() {
        return contato;
    }

    public void setContato(String contato) {
        this.contato = contato;
    }

    public Endereco getEndereco() {
        return endereco;
    }

    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getIe() {
        return ie;
    }

    public void setIe(String ie) {
        this.ie = ie;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getTelefone() {
        return telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    public Double getUnContribuicao() {
        return unContribuicao;
    }

    public void setUnContribuicao(Double unContribuicao) {
        this.unContribuicao = unContribuicao;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Associacao other = (Associacao) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + this.id;
        return hash;
    }

    @Override
    public String toString() {
        return "org.abepomi.model.Associacao";
    }



}

src/java/org/abepomi/mb/AssociadoMB.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.abepomi.mb;

import java.io.ByteArrayOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import org.abepomi.model.util.Estados;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.context.FacesContext;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.abepomi.arqs.ArqEmails;
import org.abepomi.cobranca.CobrancaBB;
import org.abepomi.dao.AssDADAO;
import org.abepomi.dao.AssociadoDAO;
import org.abepomi.dao.DAOFactory;
import org.abepomi.dao.VeiculoDAO;
import org.abepomi.dao.commons.DAOException;
import org.abepomi.dao.util.AssociadoEmail;
import org.abepomi.dao.util.AssociadoLinhaUtilRel;
import org.abepomi.dao.util.DetalheTelefoniaUtilRel;
import org.abepomi.dao.util.FaturaUtilRelCusto;
import org.abepomi.dao.util.FaturamentoRefRel;
import org.abepomi.dao.util.RefVivoRel;
import org.abepomi.mail.EmailAbepomi;
import org.abepomi.mail.EmailMensalThread;
import org.abepomi.mb.util.DownloadArq;
import org.abepomi.mb.util.GeraMd5;
import org.abepomi.model.AssDA;
import org.abepomi.model.Associado;
import org.abepomi.model.ConvDA;
import org.abepomi.model.Dependente;
import org.abepomi.model.Faturamento;
import org.abepomi.model.Linha;
import org.abepomi.model.MovDA;
import org.abepomi.model.Referencia;
import org.abepomi.model.Veiculo;
import org.abepomi.model.cobranca.Titulo;
import org.abepomi.model.util.Categoria;
import org.abepomi.model.util.EstadoDA;
import org.abepomi.model.util.EstadosCivil;
import org.abepomi.model.util.Pagto;
import org.abepomi.model.util.Parentesco;
import org.abepomi.model.util.Sexo;
import org.abepomi.model.util.Status;
import org.abepomi.model.util.Validacao;
import org.abepomi.pdf.PdfUtil;

/**
 *
 * @author Julianno
 */
public class AssociadoMB implements Serializable {

    public AssociadoMB() {
        associado = new Associado();
        dependente = new Dependente();
        veiculo = new Veiculo();

        /*
        AssociadoLinhaUtil assLU = new AssociadoLinhaUtil(1, "", new GregorianCalendar(2011, 04, 25).getTime(), new GregorianCalendar(2012, 02, 19).getTime(), 0);
        assLU.calculaProporcao(new GregorianCalendar(2012, 01, 20).getTime(), new GregorianCalendar(2012, 02, 19).getTime());
         */
    }
    private Associado associado;
    private Dependente dependente;
    private Veiculo veiculo;
    private AssDA assDA = null;
    private List<Associado> associados;
    private int selecionado;
    private String fromId;
    private String filtro;
    private String busca;
    private static AssociadoDAO assDAO = DAOFactory.createAssociadoDAO();
    //private static DependenteDAO depDAO = DAOFactory.createDependenteDAO();
    private static VeiculoDAO veiDAO = DAOFactory.createVeiculoDAO();
    private static AssDADAO daDAO = DAOFactory.createAssDADAO();
    private Referencia referencia;
    private String relNome = "";
    private Date dataInicio = null;

    public Date getDataInicio() {
        return dataInicio;
    }

    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    public List<Date> getDatasInicio() {
        if (fromId.equals("relFaturaTelefonica")) {
            Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "entrou no relFaturaTelefonica");
            return DAOFactory.createFaturaDAO().buscarDatasInicio();
        } else if (fromId.equals("relFatVivo")) {
            Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "relFatVivo");
            return DAOFactory.createFaturaVivoDAO().buscarFaturas();
        }
        Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "relFatVivoTelefonicaNULO");
        return null;
    }

    public String getRelNome() {
        return relNome;
    }

    public void setRelNome(String relNome) {
        this.relNome = relNome;
    }

    public String salvar() throws DAOException {
        String retorno = "falha";
        //try {
        try {
            if (associado.getId() == 0) {
                assDAO.addEntity(associado);
                cadastrarDA();
            } else {
                assDAO.updateEntity(associado);
            }
            retorno = "sucesso";
        } catch (DAOException ex) {
            Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "Erro: salvar()", ex);
        }
        //} finally {
        associado = new Associado();
        return retorno;
        //}



    }

    public AssDA getAssDA() {
        return assDA;
    }

    public void setAssDA(AssDA assDA) {
        this.assDA = assDA;
    }

    public Referencia getReferencia() {
        return referencia;
    }

    public void setReferencia(Referencia referencia) {
        this.referencia = referencia;
    }

    public Associado getAssociado() {
        return associado;
    }

    public void setAssociado(Associado associado) {
        this.associado = associado;
    }

    public List<Associado> getAssociados() {
        return associados;
    }

    public void setAssociados(List<Associado> associados) {
        this.associados = associados;
    }

    public String buscarAssociado() {
        try {
            if (filtro.equals("nome")) {
                associados = assDAO.buscaPorNome(busca);
            } else if (filtro.equals("cpf")) {
                associados = assDAO.buscaPorCpf(busca);
            }
        } catch (DAOException ex) {
            Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "Erro: buscarAssociado()", ex);
        }

        busca = "";
        return "pesquisar";
    }

    public String buscarTodosAssociados() {
        try {
            associados = assDAO.findAllByNome();
        } catch (DAOException ex) {
            Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "Erro: buscarTodosAssociados()", ex);
        }

        return "pesquisar";

    }

    public void setFiltro(String filtro) {
        this.filtro = filtro;
    }

    public String getFiltro() {
        return filtro;
    }

    public String getBusca() {
        return busca;
    }

    public void setBusca(String busca) {
        this.busca = busca;
    }

    public int getSelecionado() {
        return selecionado;
    }

    public void setSelecionado(int selecionado) {
        this.selecionado = selecionado;
    }

    public String selecionarAssociado() {
        try {
            associado = assDAO.findById(selecionado);
            assDA = daDAO.buscaPorAssociado(associado);
        } catch (DAOException ex) {
            Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "Erro: selecionarAssociado()", ex);
        }
        return fromId;
    }

    public String pesquisarAssociado() {
        return "pesquisar";
    }

    public String cancelar() {
        associado = new Associado();
        dependente = new Dependente();
        return "cadastro";
    }

    public Map getEstados() {
        Map<Estados, String> est = new LinkedHashMap<Estados, String>();
        for (Estados type : Estados.values()) {
            est.put(type, type.name());
        }
        return est;
    }

    public Map getParentesco() {
        Map<Parentesco, String> par = new LinkedHashMap<Parentesco, String>();
        for (Parentesco type : Parentesco.values()) {
            par.put(type, type.name());
        }
        return par;
    }

    public Map getCivil() {
        Map<EstadosCivil, String> est = new LinkedHashMap<EstadosCivil, String>();
        for (EstadosCivil type : EstadosCivil.values()) {
            est.put(type, type.name());
        }
        return est;
    }

    public Map getSexo() {
        Map<Sexo, String> sexo = new LinkedHashMap<Sexo, String>();
        for (Sexo type : Sexo.values()) {
            sexo.put(type, type.name());
        }
        return sexo;
    }

    public Map getPagto() {
        Map<Pagto, String> pagto = new LinkedHashMap<Pagto, String>();
        for (Pagto type : Pagto.values()) {
            pagto.put(type, type.name());
        }
        return pagto;
    }

    public Map getCategoria() {
        Map<Categoria, String> categoria = new LinkedHashMap<Categoria, String>();
        for (Categoria type : Categoria.values()) {
            categoria.put(type, type.name());
        }
        return categoria;
    }

    public Dependente getDependente() {
        return dependente;
    }

    public void setDependente(Dependente dependente) {
        this.dependente = dependente;
    }

    public String salvarDependente() {

        if (dependente.getId() == 0) {
            associado.getDependentes().add(dependente);
            dependente.setAssociado(associado);
        }
        try {
            assDAO.updateEntity(associado);
            associado = assDAO.findById(associado.getId());
        } catch (DAOException ex) {
            Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, "Erro: salvarDependente()", ex);
        }



        dependente = new Dependente();

        return "dependentes";
    }

    public String alterarDependente() {
        return "dependentes";
    }

    public String excluirDependente() {
        /*associado.getDependentes().remove(dependente);
        dependente.setAssociado(null);
        try {
        assDAO.updateEntity(associado);
        depDAO.updateEntity(dependente);
        depDAO.removeEntity(dependente);
        } catch (DAOException ex) {
        Logger.getLogger(AssociadoMB.class.getName()).log(Level.SEVERE, null, ex);
        }

web/telefonia/alterarcontrato.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./../template/template.xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html">
    
    <ui:define name="head">
    </ui:define>

    <ui:define name="titulo">
        ABEPOMI - Pesquisa de Contratos
    </ui:define>

    <ui:define name="divTitulo">
        Pesquisa de Contratos de Telefonia
    </ui:define>

    <ui:define name="divCentro">
        <f:view>
            <h:form id="alterarContrato" >
                <fieldset class="geral">
                    <legend>Pesquisar</legend>
                    <fieldset class="interno">
                        <h:dataTable id="dtpesquisa" value="#{teleBean.contratos}" var="contrato">
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerNumero" value="Número:" />
                                </f:facet>
                                <h:outputText id="numero" value="#{contrato.numero}" />
                            </h:column>
                            <h:column >
                                <f:facet name="header">
                                    <h:outputText id="headerDesc" value="Descrição:"  />
                                </f:facet>
                                <h:outputText id="desc" value="#{contrato.descricao}" />
                            </h:column>
                            <h:column >
                                <f:facet name="header">
                                    <h:outputText id="headerData" value="Data:"  />
                                </f:facet>
                                <h:outputText id="data" value="#{contrato.data.toLocaleString()}" />
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerSelecione" value="Selecione:" />
                                </f:facet>
                                <h:commandLink action="contratos" value="Selecionar">
                                    <f:setPropertyActionListener value="#{contrato}" target="#{teleBean.contrato}" />
                                </h:commandLink>
                            </h:column>
                        </h:dataTable>
                    </fieldset>
                </fieldset>
            </h:form>
        </f:view>
    </ui:define>

</ui:composition>

web/telefonia/alterarplano.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./../template/template.xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core">

    <ui:define name="head">
    </ui:define>

    <ui:define name="titulo">
        ABEPOMI - Pesquisa de Planos
    </ui:define>

    <ui:define name="divTitulo">
        Pesquisa de Planos
    </ui:define>

    <ui:define name="divCentro">
        <f:view>
            <h:form id="alterarPlano" >
                <fieldset class="geral">
                    <legend>Pesquisar</legend>
                    <fieldset class="interno">
                        <h:dataTable id="dtpesquisa" value="#{teleBean.planos}" var="plano">
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerDesc" value="Descrição:" />
                                </f:facet>
                                <h:outputText id="desc" value="#{plano.descricao}" />
                            </h:column>
                            <h:column >
                                <f:facet name="header">
                                    <h:outputText id="headerTipo" value="Tipo:"  />
                                </f:facet>
                                <h:outputText id="tipo" value="#{plano.tipo.toString()}" />
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText id="headerSelecione" value="Selecione:" />
                                </f:facet>
                                <h:commandLink action="planos" value="Selecionar">
                                    <f:setPropertyActionListener value="#{plano}" target="#{teleBean.plano}" />
                                </h:commandLink>
                            </h:column>
                        </h:dataTable>
                    </fieldset>
                </fieldset>
            </h:form>
        </f:view>
    </ui:define>

</ui:composition>

web/telefonia/associacao.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./../template/template.xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core">

    <ui:define name="head">
    </ui:define>

    <ui:define name="titulo">
        ABEPOMI - Cadastro de Posse de Linhas
    </ui:define>

    <ui:define name="divTitulo">
        Cadastro de Linhas para Uso da Associação
    </ui:define>

    <ui:define name="divCentro">
        <f:view>
            <h:form id="cadastroAsoLinha">
                <fieldset class="geral" id="geral">
                    <fieldset class="interno" id="interno">
                        <legend id="legendDados">Dados</legend>
                        <label id="labelLinha" for="linha">Linha:*</label>
                        <h:selectOneMenu id="linha"
                                         required="true"
                                         requiredMessage="Selecione uma linha!"
                                         value="#{teleBean.asoLinha.linha}">
                            <f:converter converterId="LinhaConverter" />
                            <f:selectItem itemLabel="Selecione" />
                            <f:selectItems value="#{teleBean.linhasLivres}"
                                           var="linhaLivre"
                                           itemLabel="#{linhaLivre.numero}"/>
                        </h:selectOneMenu>
                        <h:message id="messageLinha" for="linha" errorClass="errorMessage" />
                        <br />
                        <label id="labelFavorecido" for="favorecido">Usuário:*</label>
                        <h:inputText id="favorecido"
                                     required="true"
                                     requiredMessage="Digite o nome do usuário da linha!"
                                     value="#{teleBean.asoLinha.favorecido}"
                                     onchange="this.value = this.value.toUpperCase();"/>
                        <h:message id="messageFavorecido" for="favorecido" styleClass="errorMessage" />
                        <br />
                        <label id="labelData" for="data">Data de Entrega:*</label> <br />
                        <h:inputText id="data"
                                     required="true"
                                     requiredMessage="Digite a data de entrega da linha!"
                                     alt="date"
                                     styleClass="in160"
                                     value="#{teleBean.asoLinha.entrega}"
                                     validator="#{teleBean.validarDataEntrega}">
                            <f:converter converterId="DataConverter" />
                        </h:inputText>
                        <h:message id="messageData" for="data" styleClass="errorMessage" />
                        <br />
                        <h:commandButton value="Salvar" action="#{teleBean.salvarAssociacaoLinha}" />
                        <h:commandButton value="Limpar" immediate="true" action="#{teleBean.limparAssociacaoLinha}" />
                    </fieldset>
                </fieldset>
            </h:form>
        </f:view>
    </ui:define>

</ui:composition>

web/telefonia/associacao_devolucao.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./../template/template.xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html">
    
    <ui:define name="head">
    </ui:define>

    <ui:define name="titulo">
        ABEPOMI - Devolução de Linhas Associação
    </ui:define>

    <ui:define name="divTitulo">
        Devolução de Linhas em Uso pela Associação
    </ui:define>

    <ui:define name="divCentro">
        <f:view>
            <h:form id="formDevolucao">
                <fieldset id="geral" class="geral">
                    <fieldset id="interno" class="interno" >
                        <legend id="legendInterno">Dados</legend>
                        <label id="labelLinha" for="linha">Linha:*</label>
                        <h:selectOneMenu id="linha"
                                         required="true"
                                         requiredMessage="Selecione uma linha!"
                                         value="#{teleBean.asoLinha}"
                                         valueChangeListener="#{teleBean.carregarAsoLinha}"
                                         immediate="true" >
                            <f:converter converterId="AsoLinhaConverter" />
                            <f:selectItem itemLabel="Selecione" />
                            <f:selectItems value="#{teleBean.linhasAssociacao}"
                                           var="linhaSelecionada"
                                           itemLabel="#{linhaSelecionada.linha.numero}" />
                            <f:ajax event="change" execute="@this" render="formDevolucao:favorecido" />
                        </h:selectOneMenu>
                        <h:message id="messageLinha" for="linha" errorClass="errorMessage" />
                        <br />
                        <label id="labelFavorecido" for="favorecido">Favorecido:</label>
                        <h:inputText id="favorecido"
                                     readonly="true"
                                     value="#{teleBean.asoLinha.favorecido}" />
                        <br />
                        <label id="labelData">Devolução:*</label>
                        <h:inputText id="data"
                                     required="true"
                                     requiredMessage="Digite a data de devolução da linha!"
                                     alt="date"
                                     styleClass="in160"
                                     value="#{teleBean.asoLinha.devolucao}"
                                     validator="#{teleBean.validarDataEntrega}">
                            <f:converter converterId="DataConverter" />
                        </h:inputText>
                        <h:message id="messageData" for="data" styleClass="errorMessage" />
                        <br />
                        <h:commandButton value="Salvar" action="#{teleBean.devolverAssociacaoLinha}" />
                        <h:commandButton value="Sair" action="index" immediate="true" />
                    </fieldset>
                </fieldset>
            </h:form>
        </f:view>
    </ui:define>

</ui:composition>

web/telefonia/relfaturatelefone.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./../template/template.xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html">

    <ui:define name="head">
    </ui:define>

    <ui:define name="titulo">
        ABEPOMI - Relatório de Utilização de Serviço de Telefonia
    </ui:define>

    <ui:define name="divTitulo">
        Relatório de Utilização de Serviço de Telefonia
    </ui:define>

    <ui:define name="divCentro">
        <f:view>
            <h:form id="formReferencias" >
                <fieldset class="geral">
                    <fieldset class="interno">
                        <legend>Selecione</legend>
                        <label id="lass" for="ass">Associado:</label>
                        <h:selectOneMenu id="ass"
                                         value="#{associadoBean.associado}"
                                         required="true"
                                         requiredMessage="Selecione um associado!">
                            <f:converter converterId="AssConverter" />
                            <f:selectItem itemLabel="Selecione" />
                            <f:selectItems value="#{associadoBean.associadosNome}" var="ass" itemLabel="#{ass.nome}" />
                        </h:selectOneMenu>
                        <h:message for="ass" styleClass="errorMessage" />
                        <br />
                        <label id="lref" for="ref">Início do Período:</label><br />
                        <h:selectOneMenu id="ref"
                                         value="#{associadoBean.dataInicio}"
                                         required="true"
                                         requiredMessage="Selecione uma referência!" >
                            <f:converter converterId="DataConverter" />
                            <f:selectItem itemLabel="Selecione" />
                            <f:selectItems value="#{associadoBean.datasInicio}" var="data" itemLabel="#{data.toLocaleString()}"/>
                        </h:selectOneMenu>
                        <h:message for="ref" styleClass="errorMessage" />
                        <br />
                    </fieldset>
                    <h:commandButton id="btnsalvar" value="Gerar" action="#{associadoBean.relatorios}"/>
                </fieldset>
            </h:form>
        </f:view>
    </ui:define>

</ui:composition>